In [46]:
import numpy as np

a = np.arange(0,21,1)
b = a[::2]
c = a[3::3]
print(a)
print(b)
print(c)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 0  2  4  6  8 10 12 14 16 18 20]
[ 3  6  9 12 15 18]
